# Generated by Django 4.2.1 on 2023-05-27 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_category',
            fields=[
                ('name_of_buyer_category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id_chain', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name_of_chain', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('logo_chain', models.FileField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id_shop', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('country', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('store_address', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('opening_time_mon', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_mon', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_tues', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_tues', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_wed', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_wed', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_thur', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_thur', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_fri', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_fri', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_sat', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_sat', models.TimeField(default=datetime.time(0, 0))),
                ('opening_time_sun', models.TimeField(default=datetime.time(0, 0))),
                ('closing_time_sun', models.TimeField(default=datetime.time(0, 0))),
                ('foto_store', models.FileField(upload_to='img/')),
                ('chain', models.ManyToManyField(to='AddData.chain')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('stock', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=None)),
                ('buyer', models.ManyToManyField(to='AddData.buyer_category')),
                ('shop', models.ManyToManyField(to='AddData.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Fix_price',
            fields=[
                ('id_fix_price', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=None)),
                ('buyer', models.ManyToManyField(to='AddData.buyer_category')),
                ('shop', models.ManyToManyField(to='AddData.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id_discount', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('discount', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=None)),
                ('buyer', models.ManyToManyField(to='AddData.buyer_category')),
                ('shop', models.ManyToManyField(to='AddData.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival_of_goods',
            fields=[
                ('id_arrival', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name_of_arrival', models.CharField(default='Новое поступление', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=None)),
                ('shop', models.ManyToManyField(to='AddData.shop')),
            ],
        ),
    ]
